### ISSUE TITLE
Automated image creation for OG images

### ISSUE THREAD

**Issue by bobvanluijt** [semi-technologies/weaviate-io#49]
We currently have [OG images](https://moworks.com.au/moment/2021-04-13-open-graph-images-what-are-they-and-why-you-need-to-care#:~:text=An%20open%20graph%20image%20or,%2C%20Linkedin%2C%20Pinterest%20and%20Twitter.) for the documentation. These are now created manually but it would be great to have them automated.

Conceptually it's simple:

1) [OG location](https://github.com/semi-technologies/weaviate-io/blob/main/_includes/head.html#L36) is set to something like: `https://API-URL/?={{ page.og }}` where `page.og` is set on individual pages in the docs.
2) The [Cloud Functions](https://cloud.google.com/functions) endpoint renders a PNG or JPG like the ones Donna now manually created like [this](https://github.com/semi-technologies/weaviate-io/blob/donna-weaviate-io/img/og/og-documentation/architecture-interface.jpg).

**Comment by etiennedi** [comment]
My two cents: I think we don't even need a cloud function, we can make this even simpler since the images have to be generated just once when the website is deployed. They can then be served as static images as part of the website repo. Probably a simple python script that runs when the website is deployed should already be sufficient.

**Comment by bobvanluijt** [comment]
O yes! Even better, simply as part of the Travis job
